// ============================================
// Batch Export — PDF Zip for NeoStampa
// ============================================
// Builds a zip containing:
//   - Every unique PDF for this roll, with structured filenames
//   - The batch summary PDF (what was generated by jsPDF)
//
// Filename convention (makes it unambiguous in NeoStampa):
//   {batch#}_{invoice#}_{placement}_{Adult|Youth}_{W}x{H}_{qty}.pdf
//
// Example: 0042_38151_full-front_Adult_12x14_30.pdf
//
// If two items share the exact same filename, a sequence suffix is added.
import JSZip from 'jszip'
import type jsPDF from 'jspdf'
import { BatchItem, JobItem, JobSubmission, PLACEMENT_LABELS, Batch } from '@/types'

type EnrichedBatchItem = BatchItem & { job_item: JobItem; job: JobSubmission }

/**
 * Build a structured filename for a single item.
 */
export function buildRollFilename(
  batchNumber: number,
  item: EnrichedBatchItem,
): string {
  const placement = PLACEMENT_LABELS[item.job_item.placement]
    .toLowerCase()
    .replace(/\s+/g, '-')
  const age = item.job_item.garment_age === 'youth' ? 'Youth' : 'Adult'
  const w = item.job_item.target_width_inches
  const h = item.job_item.target_height_inches
  const batch = String(batchNumber).padStart(4, '0')
  return `${batch}_${item.job.invoice_number}_${placement}_${age}_${w}x${h}_qty${item.job_item.quantity}.pdf`
}

/**
 * Generate the zip and trigger a download in the browser.
 *
 * @param batch         The batch record
 * @param batchItems    All batch items (may contain duplicates per quantity — we dedupe by job_item_id)
 * @param fetchPdf      Function that resolves a job_item's PDF URL to a Blob. Usually wraps Supabase storage.
 * @param summaryPdf    Optional jsPDF doc for the batch summary sheet (included in the zip)
 */
export async function downloadBatchZip(
  batch: Batch,
  batchItems: EnrichedBatchItem[],
  fetchPdf: (jobItem: JobItem) => Promise<Blob>,
  summaryPdf?: jsPDF,
): Promise<void> {
  const zip = new JSZip()

  // Dedupe by job_item_id so we don't download the same PDF N times.
  const uniqueItems = new Map<string, EnrichedBatchItem>()
  for (const bi of batchItems) {
    if (!uniqueItems.has(bi.job_item_id)) {
      uniqueItems.set(bi.job_item_id, bi)
    }
  }

  // Track used filenames to avoid collisions.
  const usedNames = new Set<string>()

  for (const item of uniqueItems.values()) {
    let name = buildRollFilename(batch.batch_number, item)
    if (usedNames.has(name)) {
      // Shouldn't happen often because invoice+placement+size is usually unique,
      // but guard against it just in case.
      let suffix = 2
      while (usedNames.has(name.replace(/\.pdf$/, `_${suffix}.pdf`))) suffix++
      name = name.replace(/\.pdf$/, `_${suffix}.pdf`)
    }
    usedNames.add(name)

    try {
      const blob = await fetchPdf(item.job_item)
      zip.file(name, blob)
    } catch (err) {
      console.error(`Failed to fetch PDF for ${item.job_item.original_filename}:`, err)
      // Continue with other files rather than abort — operator should see what was packed
    }
  }

  // Include the batch summary PDF so everything is in one download.
  if (summaryPdf) {
    const summaryBlob = summaryPdf.output('blob')
    const summaryName = `0000_batch-${String(batch.batch_number).padStart(4, '0')}_SUMMARY.pdf`
    zip.file(summaryName, summaryBlob)
  }

  const zipBlob = await zip.generateAsync({ type: 'blob' })
  const url = URL.createObjectURL(zipBlob)
  const a = document.createElement('a')
  a.href = url
  a.download = `Batch-${String(batch.batch_number).padStart(4, '0')}-Roll.zip`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
